name: 'function'
description: 'Push a code function to the Nema platform.'
author: 'Nema Systems, Inc.'

inputs:
  file:
    description: 'The file that contains the function code.'
    required: true

  project:
    description:
      'Link to project in Nema. E.g., `myorganization/default/myproject`.'
    required: true

  id:
    description: 'ID of function you are updating.'
    required: true

runs:
  using: node20
  main: ../dist/function-index.js
