name: 'nema-function-update-action'
description:
  'This action updates function code in Nema, such as Python, Julia, R, ...
  code.'
author: 'Nema Systems, Inc.'

# This is what appears on GitHub Marketplace.
branding:
  icon: 'send'
  color: 'blue'

# Define your inputs here.
inputs:
  file:
    description: 'The file that contains the function code.'
    required: true

  project:
    description:
      'Link to project in Nema. E.g., `myorganization/default/myproject`.'
    required: true

  id:
    description: 'ID of function you are updating.'
    required: true

runs:
  using: node20
  main: ../dist/function-index.js
